name: Cargo fmt/test

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PATH
      run: echo ${HOME}/.cargo/bin >> $GITHUB_PATH
    - name: Run formatting
      run: cargo fmt --verbose --check
